import React from 'react';
import { Link } from 'react-router-dom';

interface PlaceholderPageProps {
  title: string;
  description?: string;
  links?: Array<{ text: string; url: string }>;
  isError?: boolean;
}

/**
 * PlaceholderPage component
 * Use this to quickly create temporary/placeholder pages when the system check detects missing pages
 */
const PlaceholderPage: React.FC<PlaceholderPageProps> = ({
  title,
  description = 'This is a placeholder page automatically generated by the system check',
  links = [],
  isError = false
}) => {
  return (
    <div className="min-h-screen bg-gray-50 flex flex-col">
      {/* Header notification bar */}
      <div className={`w-full ${isError ? 'bg-red-500' : 'bg-orange-500'} text-white py-2 px-4 text-center`}>
        <div className="container mx-auto flex items-center justify-center">
          <svg xmlns="http://www.w3.org/2000/svg" className="h-5 w-5 mr-2" viewBox="0 0 20 20" fill="currentColor">
            <path fillRule="evenodd" d="M18 10a8 8 0 11-16 0 8 8 0 0116 0zm-7-4a1 1 0 11-2 0 1 1 0 012 0zM9 9a1 1 0 000 2v3a1 1 0 001 1h1a1 1 0 100-2v-3a1 1 0 00-1-1H9z" clipRule="evenodd" />
          </svg>
          <p className="text-sm font-medium">
            {isError
              ? 'Error: This is an auto-generated placeholder for a missing page'
              : 'This is an auto-generated placeholder page'}
          </p>
        </div>
      </div>

      {/* Content */}
      <div className="flex-grow flex items-center justify-center p-4">
        <div className="bg-white shadow-lg rounded-lg max-w-2xl w-full overflow-hidden">
          {/* Header */}
          <div className={`${isError ? 'bg-red-600' : 'bg-gradient-to-r from-orange-500 to-red-500'} p-6`}>
            <h1 className="text-2xl font-bold text-white">{title}</h1>
          </div>

          {/* Body */}
          <div className="p-6">
            <div className="py-4">
              <p className="text-gray-700">{description}</p>
            </div>

            {/* Generated content */}
            <div className="bg-gray-50 border border-gray-200 rounded-lg p-6">
              <h2 className="text-lg font-medium text-gray-800 mb-4">Default Content</h2>
              
              <div className="space-y-4">
                <div className="h-12 bg-gray-100 animate-pulse rounded"></div>
                <div className="h-8 bg-gray-100 animate-pulse rounded w-2/3"></div>
                <div className="h-8 bg-gray-100 animate-pulse rounded w-3/4"></div>
              </div>

              <div className="mt-8 pt-4 border-t border-gray-200">
                <h3 className="text-md font-medium text-gray-800 mb-2">Available Navigation</h3>
                
                <div className="flex flex-wrap gap-2">
                  {links.map((link, index) => (
                    <Link
                      key={index}
                      to={link.url}
                      className="px-3 py-1 bg-gray-200 hover:bg-gray-300 rounded-md text-sm text-gray-700"
                    >
                      {link.text}
                    </Link>
                  ))}
                  
                  <Link to="/" className="px-3 py-1 bg-orange-100 hover:bg-orange-200 rounded-md text-sm text-orange-700">
                    Back to Home
                  </Link>
                </div>
              </div>
            </div>
          </div>

          {/* Footer */}
          <div className="bg-gray-50 px-6 py-3 flex justify-between items-center">
            <p className="text-xs text-gray-500">
              Generated at {new Date().toLocaleString()}
            </p>
            <button
              className="text-sm text-orange-600 hover:text-orange-800"
              onClick={() => window.location.reload()}
            >
              Reload Page
            </button>
          </div>
        </div>
      </div>
    </div>
  );
};

export default PlaceholderPage;
